### ISSUE TITLE
Provide RSS feed to your blog

### ISSUE THREAD

**Issue by giovannipds** [jugoncalves/jugoncalves.github.io#3]
Hey! I was passing by through your blog today and I've noticed you don't have RSS feed, when I tried to add the blog to my feedly account. Hove you'd like to know to add it sometime. Regards!

**Comment by jugoncalves** [comment]
YOU ARE ABSOLUTELY RIGHT

**Comment by giovannipds** [comment]
<3 glad to help. ;) Thanks for the attention.

**Comment by jugoncalves** [comment]
http://jugoncalv.es/feed.xml should be working by now.
